### ISSUE TITLE
求助，后端代码运行发生异常

### ISSUE THREAD

**Issue by qinjiakai** [Kagamia/MapRenderWeb#1]
异常信息:System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.

后端代码跑到wz_png的getRowData函数时发生的异常，wz文件用wc打开没问题，不知道是什么原因0.0

**Comment by Kagamia** [comment]
可以提供完整的游戏客户端版本与wzlib版本信息吗？

**Comment by qinjiakai** [comment]
> 可以提供完整的游戏客户端版本与wzlib版本信息吗？

wzlib的提交hash:7651d1cabb0acf5ac0fbde8cc3a110ede83fde1a
客户端版本:079

**Comment by Kagamia** [comment]
抱歉，wcR2不支持盗版客户端。
